### ISSUE TITLE
broadcast `go build` fails

### ISSUE THREAD

**Issue by bh90210** [notedit/media-server-go-demo#12]
hello there,

I am trying to reproduce the steps from the demo but when I run `go build` from `broadcast` I get this error

```bash
root@media-server-go:~/wk_webrtc/media-server-go-demo/broadcast# go build
go: downloading github.com/sanity-io/litter v1.1.0
go: downloading github.com/joho/godotenv v1.3.0
go: downloading github.com/gin-gonic/gin v1.3.0
go: downloading github.com/gorilla/websocket v1.4.0
go: extracting github.com/sanity-io/litter v1.1.0
go: extracting github.com/joho/godotenv v1.3.0
go: extracting github.com/gorilla/websocket v1.4.0
go: extracting github.com/gin-gonic/gin v1.3.0
go: downloading github.com/mattn/go-isatty v0.0.4
go: downloading github.com/gin-contrib/sse v0.0.0-20170109093832-22d885f9ecc7
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading gopkg.in/go-playground/validator.v8 v8.18.2
go: downloading github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2
go: downloading github.com/golang/protobuf v1.2.0
go: extracting github.com/gin-contrib/sse v0.0.0-20170109093832-22d885f9ecc7
go: extracting github.com/mattn/go-isatty v0.0.4
go: extracting github.com/golang/protobuf v1.2.0
go: extracting github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2
go: extracting gopkg.in/yaml.v2 v2.2.2
go: extracting gopkg.in/go-playground/validator.v8 v8.18.2
# github.com/notedit/media-server-go/wrapper
In file included from mediaserver_wrap.cxx:358:0:
../include/media-server/include/rtpsession.h:10:10: fatal error: srtp2/srtp.h: No such file or directory
 #include <srtp2/srtp.h>
          ^~~~~~~~~~~~~~
compilation terminated.
```

Also I can not build the rest of the packages. (I am getting various errors) is this behaviour expected? should I open a ticket for every error?

**Comment by notedit** [comment]
can you build  `media-server-go`  sucessfully?

**Comment by bh90210** [comment]
uh I believe so. I really didn't pay attention when I ran the commands.
re-checking asap and will let u know

**Comment by bh90210** [comment]
actually no I am sorry, you are right, I was distracted and didn't notice that it didn't build.
```bash
root@media-server-go:~/wk_webrtc/media-server-go-native# cd ../media-server-go && go build 
# github.com/notedit/media-server-go/wrapper
/usr/bin/ld: cannot find -lmediaserver
collect2: error: ld returned 1 exit status
```
should I move this issue to `media-server-go` repo?

**Comment by notedit** [comment]
that becuase you did not install the  `media-server-go-native`

I split the c++ native code to another repo  because the go tools' limit.

I will improve the build process later.

so you should install  `media-server-go-native`  and `media-server-go` before you run some demo

**Comment by bh90210** [comment]
hey @notedit yes the build process is a little confusing right now 
but I think I can build the `media-server-go-native`

I have tried the steps found here: https://github.com/notedit/media-server-go-native a couple of times and I get no error. so I assume it works. I am running it one more time as I write, just to be 100% sure.
 I will get back with the results asap. (I'm using an old laptop, takes ages to compile..)

**Comment by bh90210** [comment]
ok so I got everything working :smile: 
I am not 100% sure what the problem was but probably something related to my PATH and where I had git cloned the files originally.
```sh
root@media-server-go:/wk_webrtc/media-server-go-demo/broadcast# ./broadcast
[0x7ff100b7e740][1564218944.001][LOG]>DTLSConnection::Initialize()
[0x7ff100b7e740][1564218944.003][LOG]>DTLSConnection::GenerateCertificate()
[0x7ff100b7e740][1564218944.061][LOG]<DTLSConnection::GenerateCertificate()
[0x7ff100b7e740][1564218944.062][LOG]<DTLSConnection::Initialize(5)
[GIN-debug] [WARNING] Now Gin requires Go 1.6 or later and Go 1.7 will be required soon.

[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /channel                  --> main.channel (3 handlers)
[GIN-debug] GET    /watch/:stream            --> main.watch (3 handlers)
[GIN-debug] GET    /                         --> main.publish (3 handlers)
[GIN-debug] Listening and serving HTTP on :8000
```

anyway, fixed it, sorry for opening the issue!
thanks for your time and code!!

**Comment by kakaqi** [comment]
我编译media-server-go报错，请问是什么原因呢？

taodf@techdev ~/go/src/wk_webrtc/media-server-go $ go build
# github.com/notedit/media-server-go/wrapper
/usr/bin/ld: cannot find -lmediaserver
collect2: error: ld returned 1 exit status
