### ISSUE TITLE
Install media-server-go

### ISSUE THREAD

**Issue by 4i-helpynet** [notedit/media-server-go-demo#13]
Ubuntu 16.04
After a successful install of media-server-go-native:
root@rtc:~/wk_webrtc/media-server-go#  go build
# github.com/notedit/media-server-go/wrapper
In file included from ../include/media-server/include/rtp.h:17:0,
                 from mediaserver_wrap.cxx:356:
../include/media-server/include/rtp/RTPPacket.h:24:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.

**Comment by AlexanderKozhevin** [comment]
@notedit please, can you contact me in slack?

**Comment by AlexanderKozhevin** [comment]
@notedit
