### ISSUE TITLE
编译media-server-go 报错

### ISSUE THREAD

**Issue by kakaqi** [notedit/media-server-go-demo#14]
taodf@techdev ~/go/src/wk_webrtc/media-server-go $ go build
# github.com/notedit/media-server-go/wrapper
/usr/bin/ld: cannot find -lmediaserver
collect2: error: ld returned 1 exit status

**Comment by notedit** [comment]
需要先编译  https://github.com/notedit/media-server-go-native.git

readme中已经写了
