### ISSUE TITLE
webrtc to hls, audio

### ISSUE THREAD

**Issue by mjnk9xw** [notedit/media-server-go-demo#22]
Let me ask the pipeline command to push audio frame to ts file. Thanks :(

**Comment by AlexanderKozhevin** [comment]
@notedit can you contact me?

**Comment by mjnk9xw** [comment]
I did it. I use 2 video and audio streams to add to the ts file.

**Comment by benpeterscode1337** [comment]
@mjnk9xw hey, could you share your solution?

**Comment by mjnk9xw** [comment]
@benpeterswake  I convert 2 separate audio and video streams. video: h264parse, audio: opusparse, convert opus to voaac
pipeline of me : appsrc name=video is-live=true do-timestamp=true
					! h264parse disable-passthrough=true ! queue
					! mpegtsmux name=mux ! queue
					! hlssink sync=false playlist-length=5 max-files=10 target-duration=5 playlist-location=path/index.m3u8 location=path/fragment%05d.ts appsrc name=audio is-live=true ! opusparse ! opusdec ! audioconvert ! audio/x-raw,rate=16000 ! voaacenc ! queue ! mux.
