### ISSUE TITLE
RTMPS support ?

### ISSUE THREAD

**Issue by lakano** [notedit/media-server-go-demo#23]
Hello,
Thanks for your work!
Is it planned to support RTMPS protocol ?
We would like to stream from WebRTC to a RTMPS URL.
Regards,

**Comment by notedit** [comment]
NO,  I do not have this use case.

**Comment by rberger** [comment]
The world needs webrtc -> RTMPS. All the big guys are now only accepting RTPMS. 

Not a demand, just a wish...

I don't know enough to know how to modify your code to accomplish that on my own.
