### ISSUE TITLE
BEWARE OF MISSING PLUGINS! webrtc-to-hls files not being created.

### ISSUE THREAD

**Issue by benpeterscode1337** [notedit/media-server-go-demo#25]
I followed the readme files line for line and found that it worked perfectly when running locally, but when running on server the hls files were not being created. If you have a similar issue, check your gstreamer plugins list using this command: gst-inspect-1.0 . If you do not see this plugin 'multifile:  multifilesink: Multi-File Sink' then that is your problem. Install gstreamer using the official docs https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

**Comment by iwnow** [comment]
The same problem, when running the demo server getting this error:
GET http://localhost:8000/playlist.m3u8 404 (Not Found)

All gstreamer plugins installed
