### ISSUE TITLE
panic: create pipeline error

### ISSUE THREAD

**Issue by liping17** [notedit/media-server-go-demo#28]
0x7f261884b740][1587970433.143][LOG]>RTPTransport::Init()
[0x7f261884b740][1587970433.143][LOG]-RTPTransport::Init() | Got ports [46922,46923]
[0x7f261884b740][1587970433.143][LOG]<RTPTransport::Init()
panic: create pipeline error

goroutine 34 [running]:
github.com/notedit/media-server-go-demo/rtmp-to-webrtc/rtmpstreamer.(*RtmpStreamer).WriteHeader(0xc0001a2d80, 0xc00027ccb0, 0x1, 0x1, 0x0, 0x0)

**Comment by notedit** [comment]
check your gstreamer plugins

**Comment by TroyKomodo** [comment]
@notedit @liping17 what was the solution to this?
