### ISSUE TITLE
Not display stream

### ISSUE THREAD

**Issue by minhtien2805** [notedit/media-server-go-demo#6]
I was try demo"broadcast" , "webrtc-to-rtmp" , "rtmp-to-webrtc" everything build+start ok, but not working

- broadcast: watch/{streamid}
- rtmp-to-webrtc: Push stream to rtmp working (video/audio) but not display in html
- webrtc-to-rtmp: [0x7f0626ffd700][1561505849.605][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet

**Comment by minhtien2805** [comment]
I try in my local, endpoint default in code (endpoint := mediaserver.NewEndpoint("127.0.0.1")) 

Pls help!

**Comment by AlexanderKozhevin** [comment]
I tried webrtc-> rmtp. It works on localhost. 
But I'm getting the same error when try to run it on my server with domain attached. 
```
[0x7fe8e1f6b700][1562090983.097][DBG]-DTLSICETransport::Send() | We don't have an DTLS setup yet
```
I know it's somehow related to domain protection, but have no clue how to solve it. 
@notedit @minhtien2805 
Can you give any advice ? At least the direction?

**Comment by bas24** [comment]
same here...

Edit: Ah, well https://github.com/medooze/media-server-node/issues/46
